Public class testClass{
 //Akash
 public testClass(){
     // aa gya dosto ok. akash Pundirv VS CODE ....
 }
 public void testClass11(){
     // aa gya dosto ok. akash Pundirv VS CODE ....
 }
 public void vcs(){
     // aa gya dosto ok. akash Pundirv VS CODE ....
 }
 public void fromLocal(){
     // aa gya dosto ok. akash Pundirv VS CODE ....
 }
 public void todyFromOrg(){
     // aa gya dosto ok. akash Pundirv VS CODE ....
 }
 public void todyFromOrg11(){
     // aa gya dosto ok. akash Pundirv VS CODE ....
 }
}
